### ISSUE TITLE
Code review: Maintenance 🛠

### ISSUE THREAD

**Issue by tomasesquivelgc** [Alejuda/Awesome-books#2]
Hello Ignacio, your code looks great and is working perfectly. There isn't much to say except that in [line 37](https://github.com/Alejuda/Awesome-books/blob/main/index.js#L37) you set you set inner books as a constant with an empty string. This seems to do nothing and per good practices is best to delete. 
Keep up the good work! 😎👍

**Comment by Alejuda** [comment]
Thanks for your review!
